- hosts: teleport_nodes
  become: true
  become_method: sudo  

  tasks:
    - name: check packages
      package_facts:
        manager: auto

    - name: print
      debug:
        msg: "Version of Teleport is {{ ansible_facts.packages['teleport'][0]['version'] }}"
      when: {{ ansible_facts.packages['teleport'][0]['version'] }} != "11.1.3"

