---
- name: Daily Tasks
  hosts: all
  become: true
  become_method: sudo  
 
  tasks:
   
  - name: Check if docker is installed
    stat:
      path: /usr/bin/docker
    register: docker_installed    

  - name: Update apt repo and cache
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  
  - name: Upgrade packages
    apt: upgrade=dist force_apt_get=yes
    
  - name: Remove dependencies that are no longer required
    apt:
      autoremove: yes    

  - name: Prune Docker images
    command: docker image prune -af
    when: docker_installed.stat.exists
