---
- name: Daily Tasks
  hosts: all
  become: true
  become_method: sudo  
 
  tasks:
 
  - name: Check if Docker is installed
    stat:
      path: /usr/bin/docker
    register: docker_installed

  - name: Update apt repo and cache on all Debian/Ubuntu servers
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  
  - name: Upgrade all packages on all servers
    apt: upgrade=dist force_apt_get=yes
    
  - name: Remove dependencies that are no longer required
    apt:
      autoremove: yes    
      
  - name: Prune Docker images
    command: docker image prune -af
    when: docker_installed.stat.exists
      

#  - name: check the reboot-required file
#    register: reboot_required_file
#    stat:
#      path: /var/run/reboot-required
#    register: reboot_required_file

#  - name: launch the reboot
#    reboot:
#      msg: "Reboot with ansible..."
#      connect_timeout: 5
#      reboot_timeout: 300
#      pre_reboot_delay: 0
#      post_reboot_delay: 30
#      test_command: uptime
#    when: reboot_required_file.stat.exists
