---
- hosts: all #change to your hosts
  become: yes

  vars:
    # NOTICE!!!:
    # DO NOT PUT PLAIN TEXT PASSWORDS HERE!
    # use encrypted passwords or put them in Ansible vault
    # but this is just a demo
    vaulted_password: RbFh/9G1yxA9U

  tasks:

    - name: Add user awx with a password
      user:
        name: awx
        password: "{{ vaulted_password | password_hash('sha512') }}"
        
    - name: Add a user awx and add them to a group sudo
      user:
        name: johndoe
        groups: sudo
        append: yes        
