---
- hosts: all #change to your hosts
  become: yes

  vars:
    # NOTICE!!!:
    # DO NOT PUT PLAIN TEXT PASSWORDS HERE!
    # use encrypted passwords or put them in Ansible vault
    # but this is just a demo
    vaulted_password: $6$n/iHbufY$xsObIDdhg4Zu0ld7cxrOs1ZvSAR.HyrYgx1KJBfuNRoaPD5FJFJPYIlTy0NAH3VJpqnFwEahgAsC7/rmOMreE/


  tasks:

    - name: Add user awx with a password
      user:
        name: "{{ username }}"
        password: "{{ password }}"
        
    - name: Add a user awx and add them to a group sudo
      user:
        name: "{{ usernaame }}"
        groups: "{{ group }}"
        append: yes        
