---
- hosts: all #change to your hosts
  become: yes
  tasks:

    - name: Creating user "{{ username }}" with admin access
      user:
        name: "{{ username }}"
        password: "{{ password | password_hash('sha512') }}"
        shell: "/bin/bash"
        
    - name: Adding "{{ username }}" to group "{{ group }}" 
      user:
        name: "{{ username }}"
        groups: "{{ group }}"
        append: yes        
