- name: Servers
  hosts: all
  become: true
  become_method: sudo  
 
  tasks:

  - name: check the reboot-required file
    register: tailscale_install_req
    stat:
      path: /var/lib/tailscale/tailscaled.state
    register: tailscale_install_req

  - name: launch the reboot
    reboot:
      msg: "Reboot with ansible..."
      connect_timeout: 5
      reboot_timeout: 300
      pre_reboot_delay: 0
      post_reboot_delay: 30
      test_command: uptime
    when: tailscale_install_req == False
