- name: Tailscale install on Proxmox host starbuck
  hosts: starbuck
  roles:
    - role: artis3n.tailscale
      vars:
        # Example pulling the API key from the env vars on the host running Ansible
        tailscale_authkey: "{{ lookup('env', 'TAILSCALE_KEY') }}"
        tailscale_args: "--accept-routes=true --advertise-tags=tag:starbuck-managed"
