- hosts: teleport_nodes

  tasks:
  - name: See if teleport.yml exists
    register: teleport_required_file
    stat:
      path: /etc/teleport.yml

  - name: Test
    register: uptimeoutput
    command: "uptime"
    when: teleport_required_file.stat.exists

  - debug:
    var: uptimeoutput.stdout_lines  
    when: teleport_required_file.stat.exists
