- hosts: all,!152.67.103.175
  become: true
  become_method: sudo  
  tasks:
  
  - name: See if teleport.yaml exists
    register: teleport_required_file
    stat:
      path: /etc/teleport.yaml  
  
  - name: check packages
    package_facts:
      manager: auto
    when: 
      - teleport_required_file.stat.exists      

  - name: Download latest teleport x64 version
    apt: 
      deb: "{{ teleport_package_x64_url }}"
    when: (teleport_required_file.stat.exists) and
          (ansible_facts.packages['teleport'][0]['version'] < teleport_version) and
          (ansible_architecture == "x86_64")

