- hosts: teleport_nodes

  tasks:
  - name: See if teleport.yaml exists
    register: teleport_required_file
    stat:
      path: /etc/teleport.yaml  

  - name: Add Teleport Repo (Debian)
    become: yes
    shell: |
      sudo curl https://apt.releases.teleport.dev/gpg \
      -o /usr/share/keyrings/teleport-archive-keyring.asc
      source /etc/os-release
      echo "deb [signed-by=/usr/share/keyrings/teleport-archive-keyring.asc] \
      https://apt.releases.teleport.dev/debian {{ansible_distribution_release}} stable/v11" \
      | sudo tee /etc/apt/sources.list.d/teleport.list > /dev/null
    when: 
      - not teleport_required_file.stat.exists
      - ansible_facts['os_family'] == "Debian"    
      
  - name: Add Teleport Repo (Ubuntu)
    become: yes
    shell: |
      sudo curl https://apt.releases.teleport.dev/gpg \
      -o /usr/share/keyrings/teleport-archive-keyring.asc
      source /etc/os-release
      echo "deb [signed-by=/usr/share/keyrings/teleport-archive-keyring.asc] \
      https://apt.releases.teleport.dev/ubuntu {{ansible_distribution_release}} stable/v11" \
      | sudo tee /etc/apt/sources.list.d/teleport.list > /dev/null
    when: 
      - not teleport_required_file.stat.exists
      - ansible_facts['os_family'] == "ubuntu"      
      
#  - name: Update apt repo and cache
#    become: yes
#    apt: update_cache=yes force_apt_get=yes
   
  - name: Ansible Update Cache and install teleport
    become: yes
    apt:
      name: teleport
      state: present
    when: not teleport_required_file.stat.exists            
