- hosts: teleport_nodes
  gather_facts: no

  tasks:
  - name: See if teleport.yaml exists
    register: teleport_required_file
    stat:
      path: /etc/teleport.yaml
      
#  - name: Copy file with owner and permissions
#    become: yes
#    ansible.builtin.copy:
#      src: /scripts/teleport-repo.sh
#      dest: /opt/teleport-repo.sh
#      owner: root
#      group: root
#      mode: '0644'     
#    when: not teleport_required_file.stat.exists      
      
#  - name: Changing perm of "/opt/teleport-repo.sh", adding "+x"
#    become: yes
#    file:
#      dest: /opt/teleport-repo.sh
#      mode: a+x
#    when: not teleport_required_file.stat.exists      

  - name: Add Teleport Repo
    register: repo
    become: yes
    script: "/scripts/teleport-repo.sh"
    when: not teleport_required_file.stat.exists
    tags: repo
    
  - debug: msg="{{ repo.stdout-lines }}"    
    
  - name: Update apt repo and cache
    become: yes
    apt: update_cache=yes force_apt_get=yes
   
  - name: Ansible Update Cache and install teleport
    become: yes
    apt:
      name: teleport
      state: present
    when: not teleport_required_file.stat.exists            
