- hosts: all

  tasks:
  - name: See if teleport.yaml exists
    register: teleport_required_file
    stat:
      path: /etc/teleport.yaml

  - name: Test
    register: uptimeoutput
    command: "uptime"
    when: not teleport_required_file.stat.exists
