- hosts: teleport_nodes

  tasks:
  - name: See if teleport.yaml exists
    register: teleport_required_file
    stat:
      path: /etc/teleport.yaml  

- name: Download latest teleport version
  get_url: 
    url="{{ teleport_package_url }}"
    dest="/home/{{ ansible_env.USER }}/Downloads/{{ teleport_package_name }}.deb"
  when: 
    - teleport_required_file.stat.exists

- name: Upgrade Teleport
    apt: deb="/home/{{ ansible_env.USER }}/Downloads/{{ teleport_package_name }}.deb"
    sudo: true
