- hosts: all

  tasks:
  - name: See if teleport.yml exists
    register: teleport_required_file
    stat:
      path: /etc/teleport.yml

  - name: Test
    register: uptimeoutput
    command: "uptime"
    when: not teleport_required_file.stat.exists
