- hosts: teleport_nodes

  tasks:
  - name: See if teleport.yaml exists
    register: teleport_required_file
    stat:
      path: /etc/teleport.yaml  

- name: Download latest teleport version
  get_url: 
    url="https://cdn.teleport.dev/teleport_11.1.2_amd64.deb"
    dest="/home/awx/teleport.deb"
  when: 
    - teleport_required_file.stat.exists

- name: Upgrade Teleport
  apt: deb="/home/awx/teleport.deb"
  sudo: true
