---
- name: Update Ubuntu
  hosts: all
 
  tasks:
 
  - name: Update apt repo and cache on all Debian/Ubuntu boxes
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    become_user: root

  - name: Upgrade all packages on servers
    apt: upgrade=dist force_apt_get=yes
    become_user: root

  - name: check the reboot-required file
    register: reboot_required_file
    stat:
      path: /var/run/reboot-required
    register: reboot_required_file
    become_user: root

  - name: launch the reboot
    reboot:
      msg: "Reboot with ansible..."
      connect_timeout: 5
      reboot_timeout: 300
      pre_reboot_delay: 0
      post_reboot_delay: 30
      test_command: uptime
    when: reboot_required_file.stat.exists
    become_user: root
